services:
    sonata.admin.group:
        class: AuthBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Auth", label: "Groups" }
        arguments:
            - ~
            - AuthBundle\Entity\Group
            - SonataAdminBundle:CRUD
    sonata.admin.user:
        class: AuthBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Auth", label: "Users" }
        arguments:
            - ~
            - AuthBundle\Entity\User
            - SonataAdminBundle:CRUD
