imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AuthBundle\Entity\User
    group:
        group_class: AuthBundle\Entity\Group
    service:
        user_manager: auth.user_manager

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json', prefer_extension: false}
            - { path: '^/', priorities: ['html', '*/*'], fallback_format: 'html', prefer_extension: true }
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    view:
        formats:
            json: true
        view_response_listener: 'force'
    exception:
        messages:
            Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: true
    param_fetcher_listener: true
    serializer:
            serialize_null: false

jms_serializer:
    property_naming:
        separator:  _
        lower_case: true
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth','Session', 'Authorization', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/api/doc':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth','Session', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

nelmio_api_doc:
    name: Allyz API
    sandbox:
        enabled: true

sonata_block:
    default_contexts: [admin]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.user.block.menu:  # used to display the menu in profile pages
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:      Admin Console
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        layout:  'SonataAdminBundle::standard_layout.html.twig'
        ajax:    'SonataAdminBundle::ajax_layout.html.twig'
        list:    'SonataAdminBundle:CRUD:list.html.twig'
        show:    'SonataAdminBundle:CRUD:show.html.twig'
        edit:    'SonataAdminBundle:CRUD:edit.html.twig'
        dashboard: 'SonataAdminBundle:Core:dashboard.html.twig'
        user_block:   'AppBundle:admin:user_block.html.twig'
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        groups:

stof_doctrine_extensions:
    default_locale: en_US